# Generated by Django 5.1.7 on 2025-03-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='diploma',
            field=models.CharField(blank=True, choices=[('bachelor', 'Библиотекарь'), ('master', 'Главный библиотекарь'), ('docent', 'Директор'), ('college', 'Помощник библиотекаря')], default='none', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
